_target_: src.models.trfm.BaseNet
lr: 5e-4
weight_decay: 1e-1
lr_schedule: True
net:
  _target_: src.models.components.cnntrfm-pe.CNNTRFM_PE2
  kernel_sizes: [6, 9, 12, 15]
  out_channels: 256
  pool_size: 3
  d_model: 256
  nhead: 8
  dim_feedforward: 2048

