_target_: src.models.model.L2Net
lr: 5e-4
weight_decay: 1e-2
l2_idx: [0]
lr_schedule: True
net:
  _target_: src.models.components.danq.DanQ
  conv_out_dim: 256
  conv_kernel_size: 15
  pool_size: 3
  rnn_hidden_dim: 256
  fc_hidden_dim: 64
  dropout1: 0.2
  dropout2: 0.5

