_target_: src.models.model.L2Net
lr: 5e-4
weight_decay: 1e-1
l2_idx: [0, 4, 8, 12]
lr_schedule: True
net:
  _target_: src.models.components.deepdecode.DeepDecode
  kernel_sizes: [6, 9, 12, 15]
  out_channels:  256
  embed_dim: 256

